import { supabase } from "./supabase-client.js";
const $=id=>document.getElementById(id),esc=s=>String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const e={loginPanel:$("loginPanel"),appPanel:$("appPanel"),loginForm:$("loginForm"),loginEmail:$("loginEmail"),loginPassword:$("loginPassword"),loginMessage:$("loginMessage"),sessionEmail:$("sessionEmail"),signOutBtn:$("signOutBtn"),filter:$("inquiryFilter"),list:$("inquiryList")};
let rows=[];
async function load(){e.list.innerHTML='<p class="muted">Loading inquiries…</p>';const {data,error}=await supabase.from("gallery_inquiries").select("*").order("created_at",{ascending:false});if(error){e.list.textContent=error.message;return;}rows=data||[];await render();}
async function render(){const f=e.filter.value,visible=rows.filter(r=>!f||r.status===f||r.inquiry_type===f);e.list.innerHTML=visible.length?visible.map(r=>`<article class="panel inquiry-row" data-id="${r.id}"><div class="inquiry-row-head"><div><span class="inquiry-type">${esc(r.inquiry_type==="seller"?"Items offered":r.inquiry_type==="buyer"?"Artwork inquiry":"General inquiry")}</span><h3>${esc(r.product_title||r.name)}</h3><div class="inquiry-row-meta">${esc(r.name)} · <a href="mailto:${esc(r.email)}">${esc(r.email)}</a>${r.phone?` · <a href="tel:${esc(r.phone)}">${esc(r.phone)}</a>`:""}${r.location?` · ${esc(r.location)}`:""} · ${new Date(r.created_at).toLocaleString()}</div></div><span class="status">${esc(r.status)}</span></div><div class="inquiry-row-message">${esc(r.message)}</div><div class="inquiry-photos-admin" data-photos></div><div class="inquiry-row-actions"><a class="primary" href="mailto:${esc(r.email)}?subject=${encodeURIComponent(`Olive Vintage Gallery — ${r.product_title||"your inquiry"}`)}">Reply by email</a><select data-status><option value="new" ${r.status==="new"?"selected":""}>New</option><option value="reviewing" ${r.status==="reviewing"?"selected":""}>Reviewing</option><option value="closed" ${r.status==="closed"?"selected":""}>Closed</option></select></div></article>`).join(""):'<div class="panel inquiry-row"><p class="muted">No inquiries in this view.</p></div>';
  for(const r of visible){if(!r.image_paths?.length)continue;const {data}=await supabase.storage.from("inquiry-uploads").createSignedUrls(r.image_paths,3600);const host=e.list.querySelector(`[data-id="${r.id}"] [data-photos]`);if(host)host.innerHTML=(data||[]).filter(x=>x.signedUrl).map((x,i)=>`<a href="${esc(x.signedUrl)}" target="_blank" rel="noopener"><img src="${esc(x.signedUrl)}" alt="Submitted photo ${i+1}"></a>`).join("");}
  e.list.querySelectorAll("[data-status]").forEach(select=>select.onchange=async()=>{const id=select.closest("[data-id]").dataset.id;const {error}=await supabase.from("gallery_inquiries").update({status:select.value,updated_at:new Date().toISOString()}).eq("id",id);if(error)alert(error.message);else{const row=rows.find(r=>r.id===id);if(row)row.status=select.value;render();}});
}
e.filter.onchange=render;e.loginForm.onsubmit=async ev=>{ev.preventDefault();e.loginMessage.textContent="Signing in…";const {error}=await supabase.auth.signInWithPassword({email:e.loginEmail.value.trim(),password:e.loginPassword.value});e.loginMessage.textContent=error?error.message:"";};e.signOutBtn.onclick=()=>supabase.auth.signOut();
async function setSession(session){const admin=session?.user?.app_metadata?.olive_role==="admin";e.loginPanel.classList.toggle("hidden",admin);e.appPanel.classList.toggle("hidden",!admin);e.signOutBtn.classList.toggle("hidden",!session);e.sessionEmail.textContent=session?.user?.email||"";if(admin)await load();else if(session)e.loginMessage.textContent="This account does not have Olive Vintage owner access.";}
const {data:{session}}=await supabase.auth.getSession();await setSession(session);supabase.auth.onAuthStateChange((_event,next)=>setSession(next));
