import { supabase } from "./supabase-client.js";
const $=id=>document.getElementById(id),esc=s=>String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const e={loginPanel:$("loginPanel"),appPanel:$("appPanel"),loginForm:$("loginForm"),loginEmail:$("loginEmail"),loginPassword:$("loginPassword"),loginMessage:$("loginMessage"),sessionEmail:$("sessionEmail"),signOutBtn:$("signOutBtn"),statusFilter:$("inquiryStatusFilter"),typeFilter:$("inquiryTypeFilter"),search:$("inquirySearch"),resultCount:$("inquiryResultCount"),list:$("inquiryList"),refresh:$("refreshInquiries")};
let rows=[];
function typeLabel(type){return type==="seller"?"Items offered":type==="buyer"?"Artwork inquiry":"General inquiry";}
function ageLabel(value){const minutes=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/60000));if(minutes<2)return"Just now";if(minutes<60)return`${minutes} min ago`;const hours=Math.floor(minutes/60);if(hours<24)return`${hours} hr${hours===1?"":"s"} ago`;const days=Math.floor(hours/24);return`${days} day${days===1?"":"s"} ago`;}
function updateCounts(){const count=(test)=>rows.filter(test).length;$("countNew").textContent=count(r=>r.status==="new");$("countReviewing").textContent=count(r=>r.status==="reviewing");$("countSeller").textContent=count(r=>r.inquiry_type==="seller"&&r.status!=="closed");$("countClosed").textContent=count(r=>r.status==="closed");}
async function load(){e.list.innerHTML='<div class="panel inquiry-empty"><p>Loading inquiries…</p></div>';e.refresh.disabled=true;const {data,error}=await supabase.from("gallery_inquiries").select("*").order("created_at",{ascending:false});e.refresh.disabled=false;if(error){e.list.innerHTML=`<div class="panel inquiry-empty inquiry-error"><strong>Inbox unavailable</strong><p>${esc(error.message)}</p></div>`;return;}rows=data||[];updateCounts();await render();}
async function setStatus(id,status){const {error}=await supabase.from("gallery_inquiries").update({status,updated_at:new Date().toISOString()}).eq("id",id);if(error){alert(error.message);return false;}const row=rows.find(r=>r.id===id);if(row)row.status=status;updateCounts();await render();return true;}
async function render(){const query=e.search.value.trim().toLowerCase();const visible=rows.filter(r=>(!e.statusFilter.value||r.status===e.statusFilter.value)&&(!e.typeFilter.value||r.inquiry_type===e.typeFilter.value)&&(!query||[r.name,r.email,r.phone,r.location,r.product_title,r.message].some(v=>String(v||"").toLowerCase().includes(query))));e.resultCount.textContent=`${visible.length} of ${rows.length} request${rows.length===1?"":"s"}`;e.list.innerHTML=visible.length?visible.map(r=>{const subject=encodeURIComponent(`Olive Vintage Gallery — ${r.product_title||"your inquiry"}`),email=encodeURIComponent(r.email),phone=String(r.phone||"").replace(/[^+\d]/g,"");return`<article class="panel inquiry-row inquiry-status-${esc(r.status)}" data-id="${r.id}"><div class="inquiry-row-head"><div class="inquiry-title-block"><div class="inquiry-badges"><span class="inquiry-type">${esc(typeLabel(r.inquiry_type))}</span>${r.image_paths?.length?`<span class="inquiry-photo-count">${r.image_paths.length} photo${r.image_paths.length===1?"":"s"}</span>`:""}</div><h3>${esc(r.product_title||r.name)}</h3><div class="inquiry-person"><strong>${esc(r.name)}</strong>${r.location?`<span>${esc(r.location)}</span>`:""}</div></div><div class="inquiry-state"><span class="status status-${esc(r.status)}">${esc(r.status)}</span><time datetime="${esc(r.created_at)}" title="${esc(new Date(r.created_at).toLocaleString())}">${ageLabel(r.created_at)}</time></div></div><div class="inquiry-contact"><a href="mailto:${email}">${esc(r.email)}</a>${r.phone?`<a href="tel:${phone}">${esc(r.phone)}</a>`:""}<span>${new Date(r.created_at).toLocaleString()}</span></div><div class="inquiry-row-message">${esc(r.message)}</div><div class="inquiry-photos-admin" data-photos></div><div class="inquiry-row-actions"><a class="primary" data-reply href="mailto:${email}?subject=${subject}">Reply by email</a>${r.phone?`<a class="ghost inquiry-action" href="tel:${phone}">Call</a>`:""}<button class="ghost inquiry-action" type="button" data-copy-email="${esc(r.email)}">Copy email</button><div class="inquiry-status-actions"><label><span class="sr-only">Request status</span><select data-status><option value="new" ${r.status==="new"?"selected":""}>New</option><option value="reviewing" ${r.status==="reviewing"?"selected":""}>In review</option><option value="closed" ${r.status==="closed"?"selected":""}>Completed</option></select></label>${r.status!=="closed"?'<button class="ghost inquiry-action complete" type="button" data-complete>Mark completed</button>':'<button class="ghost inquiry-action" type="button" data-reopen>Reopen</button>'}</div></div></article>`;}).join(""):'<div class="panel inquiry-empty"><strong>No matching requests</strong><p>Try changing the status, request type, or search.</p></div>';
  for(const r of visible){if(!r.image_paths?.length)continue;const {data}=await supabase.storage.from("inquiry-uploads").createSignedUrls(r.image_paths,3600);const host=e.list.querySelector(`[data-id="${r.id}"] [data-photos]`);if(host)host.innerHTML=(data||[]).filter(x=>x.signedUrl).map((x,i)=>`<a href="${esc(x.signedUrl)}" target="_blank" rel="noopener"><img src="${esc(x.signedUrl)}" alt="Submitted photo ${i+1}"></a>`).join("");}
  e.list.querySelectorAll("[data-status]").forEach(select=>select.onchange=()=>setStatus(select.closest("[data-id]").dataset.id,select.value));
  e.list.querySelectorAll("[data-complete]").forEach(button=>button.onclick=()=>setStatus(button.closest("[data-id]").dataset.id,"closed"));
  e.list.querySelectorAll("[data-reopen]").forEach(button=>button.onclick=()=>setStatus(button.closest("[data-id]").dataset.id,"reviewing"));
  e.list.querySelectorAll("[data-reply]").forEach(link=>link.onclick=()=>{const row=rows.find(r=>r.id===link.closest("[data-id]").dataset.id);if(row?.status==="new")setStatus(row.id,"reviewing");});
  e.list.querySelectorAll("[data-copy-email]").forEach(button=>button.onclick=async()=>{await navigator.clipboard.writeText(button.dataset.copyEmail);const old=button.textContent;button.textContent="Copied";setTimeout(()=>button.textContent=old,1600);});
}
e.statusFilter.onchange=render;e.typeFilter.onchange=render;e.search.oninput=render;e.refresh.onclick=load;document.querySelectorAll("[data-quick-filter]").forEach(button=>button.onclick=()=>{const value=button.dataset.quickFilter;if(["new","reviewing","closed"].includes(value)){e.statusFilter.value=value;e.typeFilter.value="";}else{e.typeFilter.value=value;e.statusFilter.value="";}render();});e.loginForm.onsubmit=async ev=>{ev.preventDefault();e.loginMessage.textContent="Signing in…";const {error}=await supabase.auth.signInWithPassword({email:e.loginEmail.value.trim(),password:e.loginPassword.value});e.loginMessage.textContent=error?error.message:"";};e.signOutBtn.onclick=()=>supabase.auth.signOut();
async function setSession(session){const admin=session?.user?.app_metadata?.olive_role==="admin";e.loginPanel.classList.toggle("hidden",admin);e.appPanel.classList.toggle("hidden",!admin);e.signOutBtn.classList.toggle("hidden",!session);e.sessionEmail.textContent=session?.user?.email||"";if(admin)await load();else if(session)e.loginMessage.textContent="This account does not have Olive Vintage owner access.";}
const {data:{session}}=await supabase.auth.getSession();await setSession(session);supabase.auth.onAuthStateChange((_event,next)=>setSession(next));
