import { supabase } from "./supabase-client.js";
import { SUPABASE_URL, SUPABASE_ANON_KEY } from "./config.js";
const $=id=>document.getElementById(id);

// ── Mux elements ─────────────────────────────────────────────────────────────
const e={accessPanel:$("accessPanel"),accessMessage:$("accessMessage"),videoApp:$("videoApp"),sessionEmail:$("sessionEmail"),signOutBtn:$("signOutBtn"),statusPill:$("statusPill"),connectedSummary:$("connectedSummary"),tokenHint:$("tokenHint"),muxForm:$("muxForm"),tokenId:$("tokenId"),tokenSecret:$("tokenSecret"),toggleSecret:$("toggleSecret"),testBtn:$("testBtn"),disconnectBtn:$("disconnectBtn"),saveMessage:$("saveMessage")};
let session=null,status={configured:false,token_id_hint:null};
const isAdmin=()=>session?.user?.app_metadata?.olive_role==="admin";
function message(text,type=""){e.saveMessage.textContent=text||"";e.saveMessage.className=("message "+type).trim();}
function busy(on){[...e.muxForm.querySelectorAll("button,input")].forEach(x=>x.disabled=on);}
function renderStatus(){const configured=!!status.configured;e.statusPill.textContent=configured?"Mux connected":"Not connected";e.statusPill.classList.toggle("connected",configured);e.connectedSummary.classList.toggle("hidden",!configured);e.disconnectBtn.classList.toggle("hidden",!configured);e.tokenHint.textContent=status.token_id_hint?("••••••"+status.token_id_hint):"—";if(configured){e.tokenId.value="";e.tokenSecret.value="";e.tokenId.placeholder="Enter a new Token ID only when replacing the connection";e.tokenSecret.placeholder="Enter a new Token Secret only when replacing the connection";}}
async function callMux(method="GET",body=null){const{data:{session:s}}=await supabase.auth.getSession();if(!s?.access_token)throw new Error("Owner sign-in has expired. Sign in again.");const response=await fetch(SUPABASE_URL+"/functions/v1/mux-settings",{method,headers:{Authorization:"Bearer "+s.access_token,"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error||"Live-video settings request failed.");return data;}
async function loadStatus(){message("Loading secure live-video status…");try{status=await callMux("GET");renderStatus();message("");}catch(err){message(err.message,"error");}}
function renderAccess(){const ok=isAdmin();e.accessPanel.classList.toggle("hidden",ok);e.videoApp.classList.toggle("hidden",!ok);e.signOutBtn.classList.toggle("hidden",!session);e.sessionEmail.textContent=session?.user?.email||"";if(session&&!ok)e.accessMessage.textContent="This signed-in account does not have Olive Vintage owner access.";}
e.signOutBtn.onclick=async()=>{await supabase.auth.signOut();location.href="./dashboard.html";};
e.toggleSecret.onclick=()=>{const visible=e.tokenSecret.type==="text";e.tokenSecret.type=visible?"password":"text";e.toggleSecret.textContent=visible?"Show":"Hide";};
e.muxForm.onsubmit=async ev=>{ev.preventDefault();const tokenId=e.tokenId.value.trim(),tokenSecret=e.tokenSecret.value.trim();if(!tokenId||!tokenSecret){message(status.configured?"To replace the Mux connection, enter both the new Token ID and Token Secret.":"Enter both the Mux Token ID and Token Secret.","error");return;}busy(true);message("Encrypting and saving Mux credentials…");try{status=await callMux("POST",{token_id:tokenId,token_secret:tokenSecret});renderStatus();message("Mux credentials saved securely. Use Test Connection to verify them.","success");}catch(err){message(err.message,"error");}finally{busy(false);}};
e.testBtn.onclick=async()=>{busy(true);message("Testing Mux connection…");try{const result=await callMux("POST",{action:"test"});message(result.connected?"Mux connection verified. Live-video API access is working.":"Mux connection could not be verified.",result.connected?"success":"error");}catch(err){message(err.message,"error");}finally{busy(false);}};
e.disconnectBtn.onclick=async()=>{if(!confirm("Disconnect Mux from Olive Vintage? Existing auction playback URLs remain on their auction records, but new Mux broadcasts cannot be created until Mux is connected again."))return;busy(true);message("Disconnecting Mux…");try{status=await callMux("DELETE");renderStatus();message("Mux credentials removed from secure storage.","success");}catch(err){message(err.message,"error");}finally{busy(false);}};

// ── Cloudflare Realtime elements ──────────────────────────────────────────────
const cf={statusPill:$("cfStatusPill"),connectedSummary:$("cfConnectedSummary"),appIdHint:$("cfAppIdHint"),cfForm:$("cfForm"),appId:$("cfAppId"),appToken:$("cfAppToken"),toggleToken:$("cfToggleToken"),testBtn:$("cfTestBtn"),disconnectBtn:$("cfDisconnectBtn"),message:$("cfMessage")};
let cfStatus={configured:false,app_id_hint:null};
function cfMsg(text,type=""){cf.message.textContent=text||"";cf.message.className=("message "+type).trim();}
function cfBusy(on){[...cf.cfForm.querySelectorAll("button,input")].forEach(x=>x.disabled=on);}
function renderCfStatus(){const configured=!!cfStatus.configured;cf.statusPill.textContent=configured?"Cloudflare connected":"Not connected";cf.statusPill.classList.toggle("connected",configured);cf.connectedSummary.classList.toggle("hidden",!configured);cf.disconnectBtn.classList.toggle("hidden",!configured);cf.appIdHint.textContent=cfStatus.app_id_hint?("••••••"+cfStatus.app_id_hint):"—";if(configured){cf.appId.value="";cf.appToken.value="";cf.appId.placeholder="Enter a new App ID only when replacing the connection";cf.appToken.placeholder="Enter a new App Token only when replacing the connection";}}
async function callCf(method="GET",body=null){const{data:{session:s}}=await supabase.auth.getSession();if(!s?.access_token)throw new Error("Owner sign-in has expired. Sign in again.");const response=await fetch(SUPABASE_URL+"/functions/v1/cloudflare-settings",{method,headers:{Authorization:"Bearer "+s.access_token,"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error||"Cloudflare Realtime settings request failed.");return data;}
async function loadCfStatus(){cfMsg("Loading Cloudflare Realtime status…");try{cfStatus=await callCf("GET");renderCfStatus();cfMsg("");}catch(err){cfMsg(err.message,"error");}}
cf.toggleToken.onclick=()=>{const visible=cf.appToken.type==="text";cf.appToken.type=visible?"password":"text";cf.toggleToken.textContent=visible?"Show":"Hide";};
cf.cfForm.onsubmit=async ev=>{ev.preventDefault();const appId=cf.appId.value.trim(),appToken=cf.appToken.value.trim();if(!appId||!appToken){cfMsg(cfStatus.configured?"To replace the Cloudflare connection, enter both the new App ID and App Token.":"Enter both the Cloudflare Realtime App ID and App Token.","error");return;}cfBusy(true);cfMsg("Encrypting and saving Cloudflare credentials…");try{cfStatus=await callCf("POST",{app_id:appId,app_token:appToken});renderCfStatus();cfMsg("Cloudflare credentials saved securely. Use Test Connection to verify them.","success");}catch(err){cfMsg(err.message,"error");}finally{cfBusy(false);}};
cf.testBtn.onclick=async()=>{cfBusy(true);cfMsg("Testing Cloudflare Realtime connection…");try{const result=await callCf("POST",{action:"test"});cfMsg(result.connected?"Cloudflare Realtime connection verified.":"Cloudflare Realtime connection could not be verified.",result.connected?"success":"error");}catch(err){cfMsg(err.message,"error");}finally{cfBusy(false);}};
cf.disconnectBtn.onclick=async()=>{if(!confirm("Disconnect Cloudflare Realtime from Olive Vintage? Real-time presence features will be unavailable until reconnected."))return;cfBusy(true);cfMsg("Disconnecting Cloudflare Realtime…");try{cfStatus=await callCf("DELETE");renderCfStatus();cfMsg("Cloudflare credentials removed from secure storage.","success");}catch(err){cfMsg(err.message,"error");}finally{cfBusy(false);}};

// ── Boot ──────────────────────────────────────────────────────────────────────
async function boot(){const{data:{session:s}}=await supabase.auth.getSession();session=s;renderAccess();if(isAdmin()){await loadStatus();await loadCfStatus();}supabase.auth.onAuthStateChange(async(_event,next)=>{session=next;renderAccess();if(isAdmin()){await loadStatus();await loadCfStatus();}});}
boot();
